In [4]:
import numpy as np

array = np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
array[0]

array([1, 2, 3])

In [6]:
array[0,2]

3

In [12]:
display(array)
display(array[0:,1:])
display(array[:1,1:])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[2, 3],
       [5, 6],
       [8, 9]])

array([[2, 3]])

In [13]:
display(array)
display(array[2])
display(array[2,:])
display(array[2:,:])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([7, 8, 9])

array([7, 8, 9])

array([[7, 8, 9]])

In [14]:
display(array)
array[:,:2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2],
       [4, 5],
       [7, 8]])

In [16]:
display(array)
display(array[1,:2])
array[1:2,:2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([4, 5])

array([[4, 5]])